# Generated by Django 5.0.6 on 2024-06-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
