# Generated by Django 5.0.6 on 2024-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_product_count_product_image_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('count', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='product/product/')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
