# Generated by Django 5.0.6 on 2024-06-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_product_image_alter_recentproduct_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/product/'),
        ),
        migrations.AlterField(
            model_name='recentproduct',
            name='image',
            field=models.ImageField(upload_to='recent_product/recent_product/'),
        ),
    ]
