# Generated by Django 5.0.6 on 2024-06-17 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_product_image_alter_recentproduct_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recentproduct',
            name='price',
        ),
    ]
