# Generated by Django 5.0.6 on 2024-06-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_category_product_category'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
