# Generated by Django 5.0.6 on 2024-06-17 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_teams_alter_users_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users/users/'),
        ),
        migrations.AlterModelTable(
            name='teams',
            table='teams',
        ),
    ]
