# Generated by Django 5.0.6 on 2024-06-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_teams_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='position',
            field=models.CharField(max_length=50),
        ),
    ]
