# Generated by Django 5.0.6 on 2024-06-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_teams_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('chat_id', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'telegram_users',
            },
        ),
    ]
